INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(5, 'مصر  القديمه','misr alqadimuh', 14, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(6, 'جده', 'jaddah', 3, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(7, 'مصر الجديده', 'misr aljadida', 14, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(8, 'سان ستيفانو', 'San Stefano', 16, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(9, 'اكتوبر', '6 october', 15, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(10, ' الشيخ زايد', 'sheikh Zayed', 15, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(12, 'مدينه نصر', 'Nasr City', 14, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(14, ' الرياض', 'Riyadh', 2, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(15, 'الدرعية','Diriyah', 2, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(16, 'الخرج','Kharj', 2, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(17, ' العاصمة المقدسة', 'the Holy capital', 3, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(19, ' الطائف','Taif', 3, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(21, 'ينبع', 'Yanbu ', 4, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(22, 'العلا', 'Ala', 4, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(23, 'بريدة', 'Buraydah', 5, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(25, 'الرس', 'Alrass', 5, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(26, 'أبها', 'Abha', 6, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(27, 'خميس مشيط', 'Khamis Mushait', 6, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(28, 'بيشة', 'Bisha', 6, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(29, 'تبوك', 'Tabuk', 7, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(30, 'الوجه', 'alwajh', 7, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(31, 'ضبا', 'Duba ', 7, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(32, 'حائل', 'Hail', 8, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(33, 'بقعاء', 'baqea', 8, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(34, 'الغزالة', 'alghazala', 8, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(35, 'سكاكا', 'skaka', 13, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(36, 'القريات', 'Al-Qurayyat', 13, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(37, 'دومة الجندل', 'Jandal', 13, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(38, 'الباحة', 'albaha', 12, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(39, 'بلجرشي', 'Baljurashi', 12, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(40, 'المندق', 'Al-Mandak', 12, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(41, 'نجران', 'Najran', 11, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(42, 'شرورة', 'Sharurah', 11, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(43, 'حبونا', 'habuwna', 11, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(44, 'جازان', 'jazan', 10, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(45, 'صبيا', 'Sabya', 10, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(46, 'أبو عريش', 'Abu Arish', 10, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(47, 'عرعر', 'Arar', 9, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(48, 'رفحاء', 'Rafha', 9, 1);
INSERT INTO `areas`(`id`, `name_ar`, `name_en`, `city_id`, `status`) VALUES(49, 'طريف','tarif', 9, 1);

