INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (1, 'افغانستان', 'AF', 'Afghanistan', 'AFG', 4, 93, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (2, 'البانيا', 'AL', 'Albania', 'ALB', 8, 355, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (3, 'الجزائر', 'DZ', 'Algeria', 'DZA', 12, 213, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (4, 'ساموا', 'AS', 'American Samoa', 'ASM', 16, 1684, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (5, 'اندورا', 'AD', 'Andorra', 'AND', 20, 376, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (6, 'انجولا', 'AO', 'Angola', 'AGO', 24, 244, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (7, 'ANGUILLA', 'AI', 'Anguilla', 'AIA', 660, 1264, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (8, 'انتاركتيكا', 'AQ', 'Antarctica', 'ANT', 0, 0, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (9, 'ANTIGUA AND BARBUDA', 'AG', 'Antigua and Barbuda', 'ATG', 28, 1268, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (10, 'الارجنتين', 'AR', 'Argentina', 'ARG', 32, 54, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (11, 'ارمينيا', 'AM', 'Armenia', 'ARM', 51, 374, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (12, 'اروبا', 'AW', 'Aruba', 'ABW', 533, 297, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (13, 'استراليا', 'AU', 'Australia', 'AUS', 36, 61, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (14, 'AUSTRIA', 'AT', 'Austria', 'AUT', 40, 43, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (15, 'اذربيجان', 'AZ', 'Azerbaijan', 'AZE', 31, 994, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (16, 'باهاماز', 'BS', 'Bahamas', 'BHS', 44, 1242, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (17, 'البحرين', 'BH', 'Bahrain', 'BHR', 48, 973, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (18, 'بنجلادش', 'BD', 'Bangladesh', 'BGD', 50, 880, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (19, 'BARBADOS', 'BB', 'Barbados', 'BRB', 52, 1246, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (20, 'بيلاروسيا', 'BY', 'Belarus', 'BLR', 112, 375, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (21, 'بلجيكا', 'BE', 'Belgium', 'BEL', 56, 32, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (22, 'BELIZE', 'BZ', 'Belize', 'BLZ', 84, 501, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (23, 'بنين', 'BJ', 'Benin', 'BEN', 204, 229, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (24, 'BERMUDA', 'BM', 'Bermuda', 'BMU', 60, 1441, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (25, 'BHUTAN', 'BT', 'Bhutan', 'BTN', 64, 975, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (26, 'بوليفيا', 'BO', 'Bolivia', 'BOL', 68, 591, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (27, 'BOSNIA AND HERZEGOVINA', 'BA', 'Bosnia and Herzegovina', 'BIH', 70, 387, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (28, 'بوتسوانا', 'BW', 'Botswana', 'BWA', 72, 267, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (29, 'BOUVET ISLAND', 'BV', 'Bouvet Island', 'BOU', 0, 0, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (30, 'البرازيل', 'BR', 'Brazil', 'BRA', 76, 55, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (32, 'BRUNEI DARUSSALAM', 'BN', 'Brunei Darussalam', 'BRN', 96, 673, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (33, 'بلغاريا', 'BG', 'Bulgaria', 'BGR', 100, 359, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (34, 'بوركينا فاسو', 'BF', 'Burkina Faso', 'BFA', 854, 226, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (35, 'بوروندي', 'BI', 'Burundi', 'BDI', 108, 257, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (36, 'كمبوديا', 'KH', 'Cambodia', 'KHM', 116, 855, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (37, 'الكاميرون', 'CM', 'Cameroon', 'CMR', 120, 237, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (38, 'كندا', 'CA', 'Canada', 'CAN', 124, 1, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (39, 'كاب فيردي', 'CV', 'Cape Verde', 'CPV', 132, 238, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (40, 'CAYMAN ISLANDS', 'KY', 'Cayman Islands', 'CYM', 136, 1345, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (41, 'CENTRAL AFRICAN REPUBLIC', 'CF', 'Central African Republic', 'CAF', 140, 236, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (42, 'تشاد', 'TD', 'Chad', 'TCD', 148, 235, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (43, 'تشيلي', 'CL', 'Chile', 'CHL', 152, 56, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (44, 'الصين', 'CN', 'China', 'CHN', 156, 86, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (45, 'CHRISTMAS ISLAND', 'CX', 'Christmas Island', 'CHR', 0, 61, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (46, 'COCOS (KEELING) ISLANDS', 'CC', 'Cocos (Keeling) Islands', 'COC', 0, 672, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (47, 'كولومبيا', 'CO', 'Colombia', 'COL', 170, 57, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (48, 'COMOROS', 'KM', 'Comoros', 'COM', 174, 269, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (49, 'الكونجو', 'CG', 'Congo', 'COG', 178, 242, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (50, 'جمهورية الكونجو', 'CD', 'Congo, the Democratic Republic of the', 'COD', 180, 242, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (51, 'COOK ISLANDS', 'CK', 'Cook Islands', 'COK', 184, 682, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (52, 'كوستاريكا', 'CR', 'Costa Rica', 'CRI', 188, 506, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (53, 'كوت ديفوار', 'CI', 'Cote dIvoire', 'CIV', 384, 225, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (54, 'كرواتيا', 'HR', 'Croatia', 'HRV', 191, 385, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (55, 'كوبا', 'CU', 'Cuba', 'CUB', 192, 53, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (56, 'CYPRUS', 'CY', 'Cyprus', 'CYP', 196, 357, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (57, 'التشيك', 'CZ', 'Czech Republic', 'CZE', 203, 420, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (58, 'الدانمارك', 'DK', 'Denmark', 'DNK', 208, 45, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (59, 'جيبوتي', 'DJ', 'Djibouti', 'DJI', 262, 253, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (60, 'DOMINICA', 'DM', 'Dominica', 'DMA', 212, 1767, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (61, 'DOMINICAN REPUBLIC', 'DO', 'Dominican Republic', 'DOM', 214, 1809, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (62, 'الاكوادور', 'EC', 'Ecuador', 'ECU', 218, 593, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (63, 'مصر', 'EG', 'Egypt', 'EGY', 818, 20, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (64, 'السلفادور', 'SV', 'El Salvador', 'SLV', 222, 503, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (65, 'EQUATORIAL GUINEA', 'GQ', 'Equatorial Guinea', 'GNQ', 226, 240, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (66, 'اريتريا', 'ER', 'Eritrea', 'ERI', 232, 291, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (67, 'استونيا', 'EE', 'Estonia', 'EST', 233, 372, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (68, 'اثيوبيا', 'ET', 'Ethiopia', 'ETH', 231, 251, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (69, 'FALKLAND ISLANDS (MALVINAS)', 'FK', 'Falkland Islands (Malvinas)', 'FLK', 238, 500, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (70, 'FAROE ISLANDS', 'FO', 'Faroe Islands', 'FRO', 234, 298, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (71, 'FIJI', 'FJ', 'Fiji', 'FJI', 242, 679, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (72, 'فنلندا', 'FI', 'Finland', 'FIN', 246, 358, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (73, 'فرنسا', 'FR', 'France', 'FRA', 250, 33, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (74, 'FRENCH GUIANA', 'GF', 'French Guiana', 'GUF', 254, 594, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (75, 'FRENCH POLYNESIA', 'PF', 'French Polynesia', 'PYF', 258, 689, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (76, 'FRENCH SOUTHERN TERRITORIES', 'TF', 'French Southern Territories', 'TFS', 0, 0, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (77, 'الجابون', 'GA', 'Gabon', 'GAB', 266, 241, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (78, 'جامبيا', 'GM', 'Gambia', 'GMB', 270, 220, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (79, 'جورجيا', 'GE', 'Georgia', 'GEO', 268, 995, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (80, 'المانيا', 'DE', 'Germany', 'DEU', 276, 49, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (81, 'غانا', 'GH', 'Ghana', 'GHA', 288, 233, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (82, 'GIBRALTAR', 'GI', 'Gibraltar', 'GIB', 292, 350, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (83, 'اليونيا', 'GR', 'Greece', 'GRC', 300, 30, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (84, 'GREENLAND', 'GL', 'Greenland', 'GRL', 304, 299, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (85, 'غرناطة', 'GD', 'Grenada', 'GRD', 308, 1473, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (86, 'GUADELOUPE', 'GP', 'Guadeloupe', 'GLP', 312, 590, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (87, 'GUAM', 'GU', 'Guam', 'GUM', 316, 1671, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (88, 'غواتيمالا', 'GT', 'Guatemala', 'GTM', 320, 502, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (89, 'غينيا', 'GN', 'Guinea', 'GIN', 324, 224, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (90, 'غينيا بيساو', 'GW', 'Guinea-Bissau', 'GNB', 624, 245, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (91, 'GUYANA', 'GY', 'Guyana', 'GUY', 328, 592, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (92, 'هاييتي', 'HT', 'Haiti', 'HTI', 332, 509, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (94, 'HOLY SEE (VATICAN CITY STATE)', 'VA', 'Holy See (Vatican City State)', 'VAT', 336, 39, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (95, 'هندوراس', 'HN', 'Honduras', 'HND', 340, 504, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (96, 'هونج كونج', 'HK', 'Hong Kong', 'HKG', 344, 852, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (97, 'المجر', 'HU', 'Hungary', 'HUN', 348, 36, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (98, 'ايسلندا', 'IS', 'Iceland', 'ISL', 352, 354, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (99, 'الهند', 'IN', 'India', 'IND', 356, 91, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (100, 'اندونيسيا', 'ID', 'Indonesia', 'IDN', 360, 62, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (101, 'ايران', 'IR', 'Iran, Islamic Republic of', 'IRN', 364, 98, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (102, 'العراق', 'IQ', 'Iraq', 'IRQ', 368, 964, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (103, 'ايرلندا', 'IE', 'Ireland', 'IRL', 372, 353, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (104, 'اسرائيل', 'IL', 'Israel', 'ISR', 376, 972, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (105, 'ايطاليا', 'IT', 'Italy', 'ITA', 380, 39, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (106, 'جامايكا', 'JM', 'Jamaica', 'JAM', 388, 1876, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (107, 'اليابان', 'JP', 'Japan', 'JPN', 392, 81, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (108, 'الاردن', 'JO', 'Jordan', 'JOR', 400, 962, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (109, 'كازاخستان', 'KZ', 'Kazakhstan', 'KAZ', 398, 7, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (110, 'كينيا', 'KE', 'Kenya', 'KEN', 404, 254, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (111, 'KIRIBATI', 'KI', 'Kiribati', 'KIR', 296, 686, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (112, 'KOREA, DEMOCRATIC PEOPLE REPUBLIC OF', 'KP', 'Korea, Democratic People Republic of', 'PRK', 408, 850, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (113, 'KOREA, REPUBLIC OF', 'KR', 'Korea, Republic of', 'KOR', 410, 82, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (114, 'الكويت', 'KW', 'Kuwait', 'KWT', 414, 965, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (115, 'KYRGYZSTAN', 'KG', 'Kyrgyzstan', 'KGZ', 417, 996, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (116, 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'LA', 'Lao People\'s Democratic Republic', 'LAO', 418, 856, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (117, 'لاتيفيا', 'LV', 'Latvia', 'LVA', 428, 371, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (118, 'لبنان', 'LB', 'Lebanon', 'LBN', 422, 961, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (119, 'ليسوتو', 'LS', 'Lesotho', 'LSO', 426, 266, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (120, 'ليبريا', 'LR', 'Liberia', 'LBR', 430, 231, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (121, 'ليبيا', 'LY', 'Libyan Arab Jamahiriya', 'LBY', 434, 218, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (122, 'LIECHTENSTEIN', 'LI', 'Liechtenstein', 'LIE', 438, 423, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (123, 'ليتوانيا', 'LT', 'Lithuania', 'LTU', 440, 370, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (124, 'لوكسمبرج', 'LU', 'Luxembourg', 'LUX', 442, 352, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (125, 'ماكاو', 'MO', 'Macao', 'MAC', 446, 853, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (126, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807, 389, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (127, 'مدغشقر', 'MG', 'Madagascar', 'MDG', 450, 261, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (128, 'مالاوي', 'MW', 'Malawi', 'MWI', 454, 265, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (129, 'ماليزيا', 'MY', 'Malaysia', 'MYS', 458, 60, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (130, 'مالديف', 'MV', 'Maldives', 'MDV', 462, 960, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (131, 'مالي', 'ML', 'Mali', 'MLI', 466, 223, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (132, 'مالطا', 'MT', 'Malta', 'MLT', 470, 356, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (133, 'MARSHALL ISLANDS', 'MH', 'Marshall Islands', 'MHL', 584, 692, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (134, 'MARTINIQUE', 'MQ', 'Martinique', 'MTQ', 474, 596, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (135, 'MAURITANIA', 'MR', 'Mauritania', 'MRT', 478, 222, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (136, 'MAURITIUS', 'MU', 'Mauritius', 'MUS', 480, 230, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (138, 'المكسيك', 'MX', 'Mexico', 'MEX', 484, 52, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (139, 'MICRONESIA, FEDERATED STATES OF', 'FM', 'Micronesia, Federated States of', 'FSM', 583, 691, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (140, 'MOLDOVA, REPUBLIC OF', 'MD', 'Moldova, Republic of', 'MDA', 498, 373, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (141, 'موناكو', 'MC', 'Monaco', 'MCO', 492, 377, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (142, 'منغوليا', 'MN', 'Mongolia', 'MNG', 496, 976, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (143, 'MONTSERRAT', 'MS', 'Montserrat', 'MSR', 500, 1664, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (144, 'المغرب', 'MA', 'Morocco', 'MAR', 504, 212, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (145, 'موزمبيق', 'MZ', 'Mozambique', 'MOZ', 508, 258, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (146, 'ميانمار', 'MM', 'Myanmar', 'MMR', 104, 95, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (147, 'ناميبيا', 'NA', 'Namibia', 'NAM', 516, 264, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (148, 'NAURU', 'NR', 'Nauru', 'NRU', 520, 674, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (149, 'نيبال', 'NP', 'Nepal', 'NPL', 524, 977, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (150, 'هولندا', 'NL', 'Netherlands', 'NLD', 528, 31, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (151, 'NETHERLANDS ANTILLES', 'AN', 'Netherlands Antilles', 'ANT', 530, 599, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (152, 'NEW CALEDONIA', 'NC', 'New Caledonia', 'NCL', 540, 687, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (153, 'نيوزيلندا', 'NZ', 'New Zealand', 'NZL', 554, 64, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (154, 'نيكاراجوا', 'NI', 'Nicaragua', 'NIC', 558, 505, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (155, 'نيجر', 'NE', 'Niger', 'NER', 562, 227, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (156, 'نيجريا', 'NG', 'Nigeria', 'NGA', 566, 234, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (157, 'NIUE', 'NU', 'Niue', 'NIU', 570, 683, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (158, 'NORFOLK ISLAND', 'NF', 'Norfolk Island', 'NFK', 574, 672, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (159, 'NORTHERN MARIANA ISLANDS', 'MP', 'Northern Mariana Islands', 'MNP', 580, 1670, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (160, 'نورواي', 'NO', 'Norway', 'NOR', 578, 47, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (161, 'عمان', 'OM', 'Oman', 'OMN', 512, 968, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (162, 'باكستان', 'PK', 'Pakistan', 'PAK', 586, 92, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (163, 'PALAU', 'PW', 'Palau', 'PLW', 585, 680, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (165, 'بنما', 'PA', 'Panama', 'PAN', 591, 507, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (166, 'PAPUA NEW GUINEA', 'PG', 'Papua New Guinea', 'PNG', 598, 675, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (167, 'باراجواي', 'PY', 'Paraguay', 'PRY', 600, 595, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (168, 'بيرو', 'PE', 'Peru', 'PER', 604, 51, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (169, 'PHILIPPINES', 'PH', 'Philippines', 'PHL', 608, 63, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (170, 'PITCAIRN', 'PN', 'Pitcairn', 'PCN', 612, 0, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (171, 'بولندا', 'PL', 'Poland', 'POL', 616, 48, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (172, 'البرتغال', 'PT', 'Portugal', 'PRT', 620, 351, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (173, 'برتوريكو', 'PR', 'Puerto Rico', 'PRI', 630, 1787, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (174, 'قطر', 'QA', 'Qatar', 'QAT', 634, 974, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (175, 'REUNION', 'RE', 'Reunion', 'REU', 638, 262, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (176, 'رومانيا', 'RO', 'Romania', 'ROM', 642, 40, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (177, 'روسيا', 'RU', 'Russian Federation', 'RUS', 643, 70, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (178, 'رواندا', 'RW', 'Rwanda', 'RWA', 646, 250, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (179, 'SAINT HELENA', 'SH', 'Saint Helena', 'SHN', 654, 290, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (180, 'SAINT KITTS AND NEVIS', 'KN', 'Saint Kitts and Nevis', 'KNA', 659, 1869, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (181, 'SAINT LUCIA', 'LC', 'Saint Lucia', 'LCA', 662, 1758, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (182, 'SAINT PIERRE AND MIQUELON', 'PM', 'Saint Pierre and Miquelon', 'SPM', 666, 508, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (183, 'SAINT VINCENT AND THE GRENADINES', 'VC', 'Saint Vincent and the Grenadines', 'VCT', 670, 1784, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (184, 'ساموا', 'WS', 'Samoa', 'WSM', 882, 684, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (185, 'سان مارينو', 'SM', 'San Marino', 'SMR', 674, 378, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (186, 'SAO TOME AND PRINCIPE', 'ST', 'Sao Tome and Principe', 'STP', 678, 239, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (187, 'السعودية', 'SA', 'Saudi Arabia', 'SAU', 682, 966, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (188, 'السنغال', 'SN', 'Senegal', 'SEN', 686, 221, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (190, 'SEYCHELLES', 'SC', 'Seychelles', 'SYC', 690, 248, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (191, 'SIERRA LEONE', 'SL', 'Sierra Leone', 'SLE', 694, 232, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (192, 'سنغافورة', 'SG', 'Singapore', 'SGP', 702, 65, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (193, 'سلوفاكيا', 'SK', 'Slovakia', 'SVK', 703, 421, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (194, 'سلوفينيا', 'SI', 'Slovenia', 'SVN', 705, 386, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (195, 'SOLOMON ISLANDS', 'SB', 'Solomon Islands', 'SLB', 90, 677, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (196, 'الصومال', 'SO', 'Somalia', 'SOM', 706, 252, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (197, 'جنوب افريقيا', 'ZA', 'South Africa', 'ZAF', 710, 27, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (198, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS', 'South Georgia and the South Sandwich Islands', NULL, NULL, 0, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (199, 'اسبانيا', 'ES', 'Spain', 'ESP', 724, 34, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (200, 'سريلانكا', 'LK', 'Sri Lanka', 'LKA', 144, 94, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (201, 'السودان', 'SD', 'Sudan', 'SDN', 736, 249, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (202, 'سورينام', 'SR', 'Suriname', 'SUR', 740, 597, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (203, 'SVALBARD AND JAN MAYEN', 'SJ', 'Svalbard and Jan Mayen', 'SJM', 744, 47, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (204, 'سوازيلاند', 'SZ', 'Swaziland', 'SWZ', 748, 268, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (205, 'السويد', 'SE', 'Sweden', 'SWE', 752, 46, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (206, 'سويزيلاند', 'CH', 'Switzerland', 'CHE', 756, 41, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (207, 'سوريا', 'SY', 'Syrian Arab Republic', 'SYR', 760, 963, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (208, 'TAIWAN, PROVINCE OF CHINA', 'TW', 'Taiwan, Province of China', 'TWN', 158, 886, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (209, 'طاجاكستان', 'TJ', 'Tajikistan', 'TJK', 762, 992, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (210, 'تنزانيا', 'TZ', 'Tanzania, United Republic of', 'TZA', 834, 255, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (211, 'تايلاند', 'TH', 'Thailand', 'THA', 764, 66, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (213, 'توجو', 'TG', 'Togo', 'TGO', 768, 228, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (214, 'TOKELAU', 'TK', 'Tokelau', 'TKL', 772, 690, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (215, 'تونجا', 'TO', 'Tonga', 'TON', 776, 676, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (216, 'ترينداد وتوباجو', 'TT', 'Trinidad and Tobago', 'TTO', 780, 1868, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (217, 'تونس', 'TN', 'Tunisia', 'TUN', 788, 216, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (218, 'تركيا', 'TR', 'Turkey', 'TUR', 792, 90, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (219, 'تركمانستان', 'TM', 'Turkmenistan', 'TKM', 795, 7370, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (220, 'TURKS AND CAICOS ISLANDS', 'TC', 'Turks and Caicos Islands', 'TCA', 796, 1649, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (221, 'TUVALU', 'TV', 'Tuvalu', 'TUV', 798, 688, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (222, 'اوغندا', 'UG', 'Uganda', 'UGA', 800, 256, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (223, 'اوكرانيا', 'UA', 'Ukraine', 'UKR', 804, 380, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (224, 'الامارات', 'AE', 'United Arab Emirates', 'ARE', 784, 971, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (225, 'انجلترا', 'GB', 'United Kingdom', 'GBR', 826, 44, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (226, 'امريكا', 'US', 'United States', 'USA', 840, 1, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (228, 'اوروجواي', 'UY', 'Uruguay', 'URY', 858, 598, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (229, 'اوزباكستان', 'UZ', 'Uzbekistan', 'UZB', 860, 998, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (230, 'VANUATU', 'VU', 'Vanuatu', 'VUT', 548, 678, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (231, 'فنزويلا', 'VE', 'Venezuela', 'VEN', 862, 58, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (232, 'فيتنام', 'VN', 'Viet Nam', 'VNM', 704, 84, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (233, 'VIRGIN ISLANDS, BRITISH', 'VG', 'Virgin Islands, British', 'VGB', 92, 1284, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (234, 'VIRGIN ISLANDS, U.S.', 'VI', 'Virgin Islands, U.s.', 'VIR', 850, 1340, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (235, 'WALLIS AND FUTUNA', 'WF', 'Wallis and Futuna', 'WLF', 876, 681, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (236, 'WESTERN SAHARA', 'EH', 'Western Sahara', 'ESH', 732, 212, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (237, 'اليمن', 'YE', 'Yemen', 'YEM', 887, 967, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (238, 'زامبيا', 'ZM', 'Zambia', 'ZMB', 894, 260, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (239, 'زيمبابوي', 'ZW', 'Zimbabwe', 'ZWE', 716, 263, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (240, 'صربيا', 'RS', 'Serbia', 'SRB', 688, 381, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (241, 'ASIA PACIFIC REGION', 'AP', 'Asia / Pacific Region', '0', 0, 0, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (242, 'مونتنجرو', 'ME', 'Montenegro', 'MNE', 499, 382, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (243, 'ALAND ISLANDS', 'AX', 'Aland Islands', 'ALA', 248, 358, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (244, 'BONAIRE, SINT EUSTATIUS AND SABA', 'BQ', 'Bonaire, Sint Eustatius and Saba', 'BES', 535, 599, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (245, 'CURACAO', 'CW', 'Curacao', 'CUW', 531, 599, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (246, 'GUERNSEY', 'GG', 'Guernsey', 'GGY', 831, 44, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (247, 'ISLE OF MAN', 'IM', 'Isle of Man', 'IMN', 833, 44, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (248, 'JERSEY', 'JE', 'Jersey', 'JEY', 832, 44, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (249, 'KOSOVO', 'XK', 'Kosovo', '---', 0, 381, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (250, 'SAINT BARTHELEMY', 'BL', 'Saint Barthelemy', 'BLM', 652, 590, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (251, 'SAINT MARTIN', 'MF', 'Saint Martin', 'MAF', 663, 590, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (252, 'SINT MAARTEN', 'SX', 'Sint Maarten', 'SXM', 534, 1, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (253, 'جنوب السودان', 'SS', 'South Sudan', 'SSD', 728, 211, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (254, 'Egypt', 'EG', 'Egypt', 'EG', 818, 20, 1);
INSERT INTO `countries`(`id`, `name_ar`, `country_code`,`name_en`,  `iso3`, `numcode`, `phonecode`, `status`) VALUES (255, 'Saudi', 'SA', 'Saudi Arabia', 'SA', 682, 966, 1);
